# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoftVisionPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
	pod 'Kingfisher', '~> 4.10.1'
  # Pods for SoftVisionPOC

  target 'SoftVisionPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoftVisionPOCUITests' do
    # Pods for testing
  end

end
